INSERT INTO `contenido`(`producto`, `texto`) VALUES ( 1 ,'Modelo dorado y negro del popular YAS-875EX ,  el saxofón insignia del fabricante japonés para los músicos clásicos más exigentes! El nuevo saxofón alto Yamaha YAS-875EXS marca un gran avance en el diseño de saxofones, ofreciendo a los saxofonistas una gran cantidad de nuevas posibilidades musicales. Custom 875EX ha sido diseñado en colaboración con los intérpretes más talentosos del mundo, incluyendo a Nobuya Sugawa, Jean-Yves Fourmeau y Otis Murphy. Gracias a su inestimable aportación, Yamaha ha sido capaz de crear un instrumento que suena increíble y que ofrece al intérprete una total libertad expresiva.
    La serie de saxofones altos Custom 875 de Yamaha mejoran la acción, son saxos ágiles y rápidos, con un amplio rango dinámico. Mantienen una equilibrada proyección traducida en un bello timbre. Pronto notarás la profundidad y la delicadeza de su sonido, simplemente increíble. Además, este saxofón alto aporta una enorme flexibilidad a la hora de interpretar cualquier género musical.
    El tamaño y la forma de las llaves se han modificado para mejorar la "sensación" al interpretarlo. Los nuevos tudeles V1 mejoran la resonancia, proporcionando una respuesta más rápida y cómoda. Finalmente, estos saxofones incluyen un soporte de unión entre campana y cuerpo con dos puntos de sujeción, mejorando su rendimiento. </p>
  Características:
- Material: Latón
- Acabado: Plateado
- Puladores o teclas de acción: Nácar blanco
- Tudel: Yamaha V1
- Grabado: Grabado a mano en campana y codo
- Estuche: Yamaha Custom rectangular con opción mochila
- Boquilla: El saxofón Custom EX se complementa con la boquilla de ebonita rediseñada por Yamaha. El baffle, la cámara y los railes han sido rediseñadas para una mayor proyección, así como una sonoridad suave y hermosa. La forma de la punta ha sido modificada para aumentar la comodidad y facilitar el control de la emisión.
- Boquilla: El saxofón Custom EX se complementa con la boquilla de ebonita rediseñada por Yamaha. El baffle, la cámara y los railes han sido rediseñadas para una mayor proyección, así como una sonoridad suave y hermosa. La forma de la punta ha sido modificada para aumentar la comodidad y facilitar el control de la emisión.');