INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 1 ,'images/saxo_soprano.png'); 
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 2 ,'images/saxo_alto.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 3 ,'images/saxo_tenor.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 4 ,'images/saxo_baritono.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 5 ,'images/boquilla_selmer_c1.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 6 ,'images/boquilla_selmer_concept.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 7 ,'images/boquilla_vandoren_al3.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 8 ,'images/canias_vandoren.png');
INSERT INTO `imagenes`(`producto`, `recurso`) VALUES ( 9 ,'images/brazadera_bg.png');